apiVersion: 1

datasources:

- name: Tempo
  type: tempo
  uid: tempo-uid
  access: proxy
  url: http://tempo:3200
  basicAuth: false
  isDefault: true
  version: 1
  editable: true
  readOnly: false
  apiVersion: 1
  jsonData:
    httpMethod: GET
    tracesToLogsV2:
      datasourceUid: loki-uid
      spanStartTimeShift: '-1h'
      spanEndTimeShift: '1h'
      filterByTraceID: true
      filterBySpanID: true
      customQuery: false
    nodeGraph:
      enabled: true
    search:
      hide: false
    traceQuery:
      timeShiftEnabled: true
      spanStartTimeShift: '-1h'
      spanEndTimeShift: '1h'
    spanBar:
      type: 'Tag'
      tag: 'http.path'

- name: Loki
  type: loki
  uid: loki-uid
  access: proxy
  url: http://loki:3100
  basicAuth: false
  isDefault: false
  version: 1
  editable: true
  readOnly: false
  jsonData:
    derivedFields:
      - datasourceUid: tempo-uid
        matcherRegex: "\"[tT][rR][aA][cC][eE][iI][dD]\":\"?([a-fA-F0-9]+)\"?"
        name: TraceId
        url: $${__value.raw}
