@usersApiHost = http://localhost:8088/users

GET {{usersApiHost}}

### Existing user

GET {{usersApiHost}}/192366d3-51bc-43ac-8de1-13bda0b66038

### Non-existent user

GET {{usersApiHost}}/1ab4e8c5-931a-4b7f-99d2-dba8aca287b8

###

POST {{usersApiHost}}
Content-Type: application/json

{
    "name": "Fake User",
    "email": "fake@fake.fk",
    "phone": "1234"
}

###

PUT {{usersApiHost}}/e4422c63-fc51-43b2-9a63-74fdb8939b13
Content-Type: application/json

{
    "name": "Fake User Update",
    "email": "fake@Update.fk",
    "phone": "12341112"
}

###

DELETE {{usersApiHost}}/64c76e00-ce3c-4967-8e50-3d5a972a0cc7
